## Gluon sample example

Here in this section we will try to explore some sor t of Gluon API.


In [4]:
#imperative example
import mxnet as mx
from mxnet import nd
a = mx.nd.zeros((120,60))
b = mx.nd.zeros((120,60))
c = a + b
c += 1
print (c)



[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
<NDArray 120x60 @cpu(0)>


In [1]:
#Symbolic
import mxnet as mx
from mxnet import nd
net = mx.sym.Variable('data')
net = mx.sym.FullyConnected(data=net, num_hidden=10)
net = mx.sym.SoftmaxOutput(data=net)
texec = mx.module.Module(net)
texec.forward(data=c)
texec.backward()

/Users/maheshwarligade/miniconda3/envs/gluon/lib/python3.7/site-packages/mxnet/module/base_module.py:56: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
	softmaxoutput0_label
  warnings.warn(msg)


NameError: name 'c' is not defined

## NDArray API

NDArray API are the core API in mxnet to store, manipulate and transform the data. NDArray is similar like a Numpy API.

### Array creation in NDArray

In [2]:
# create Array using python list or tuple
import mxnet as mx
# create a one-dimensional array with a python list
x = mx.nd.array([4,3,9])
# create a 2-dimensional array with a nested python list
z = mx.nd.array([[4,3,6], [5,1,8]])
{'x.shape':x.shape, 'z.shape':z.shape}

{'x.shape': (3,), 'z.shape': (2, 3)}

### creation of a array using numpy 

In [11]:
import numpy as np

d = np.arange(15).reshape(3,5)
# create a 2-dimensional array from a numpy.ndarray object
y = mx.nd.array(d)
{'y.shape':y.shape}
x


[4. 3. 9.]
<NDArray 3 @cpu(0)>

In [25]:
# basic operatiosn of NDArray
# float32 is used by default
a = mx.nd.array([1,2,3])
# create a 16-bit float array
c = mx.nd.array([1.2, 2.3], dtype=np.float16)
(a.dtype, c.dtype)
# create empty array
d = mx.nd.empty((2,3))
# create array with all zeros
e = mx.nd.zeros((2,3))
# create array with all 5
f = mx.nd.full((2,3),5)
# we can also perform some basic operations
# elementwise plus
g = d + e
# elementwise minus
h = d-e
i = -e
# we can use sum or mean 
j = mx.nd.sum(e)
# exponential
j.exp()
# transpose matrix
nd.dot(a,c.T)
#indexing
j[1,2]
# for advanced way
j[:,1:2]


[1.]
<NDArray 1 @cpu(0)>

In [24]:
# convert x into numpy z array
z = x.asnumpy()
# display type of z for verification
(type(z), z)
# display numpy array as a NDArray.
nd.array(z)
z

array([4., 3., 9.], dtype=float32)

### Symbol API
Symbol API also the one of the core API of mxnet framework. This is the crucial one

In [1]:
import mxnet as mx
a = mx.sym.Variable('a')
b = mx.sym.Variable('b')
c = 3 * a + b
type(c)

mxnet.symbol.symbol.Symbol

## creat simple neural network 

In [5]:
# import ndarray module from mxnet package
from mxnet import nd
# import gluon package
from mxnet.gluon import nn

# let us define layer Dense is a subclass of Block to define layer
layer = nn.Dense(2)
layer


Dense(None -> 2, linear)

In [16]:

# we need to initialise the weight [-0.7,0.7]
layer.initialize(ctx=mx.cpu(0))
# random (3,4) matrix range from -1 to 1
x = nd.random.uniform(-1,1,shape=(3,4))
layer(x)



[[ 0.01587485  0.03087313]
 [ 0.02257253 -0.02103142]
 [ 0.06961896  0.01239835]]
<NDArray 3x2 @cpu(0)>

In [11]:
layer.weight.data()


[[-0.00873779 -0.02834515  0.05484822 -0.06206018]
 [ 0.06491279 -0.03182812 -0.01631819 -0.00312688]]
<NDArray 2x4 @cpu(0)>

In [17]:
layer.collect_params()

dense3_ (
  Parameter dense3_weight (shape=(2, 4), dtype=float32)
  Parameter dense3_bias (shape=(2,), dtype=float32)
)

In [20]:
type(layer.collect_params())

mxnet.gluon.parameter.ParameterDict